// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9LbjWBeKL7jbpZmRL2Au4leq5bEIo0Y',
    appId: '1:536987531282:web:2de8ec291bef220e9cc0cb',
    messagingSenderId: '536987531282',
    projectId: 'taskflow-a6f6e',
    authDomain: 'taskflow-a6f6e.firebaseapp.com',
    storageBucket: 'taskflow-a6f6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHq-QtanD6D92E7YhWT8NFA_IkZVHFo6Y',
    appId: '1:536987531282:android:abb70a6971328c8a9cc0cb',
    messagingSenderId: '536987531282',
    projectId: 'taskflow-a6f6e',
    storageBucket: 'taskflow-a6f6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_aq_1uEhml4sdiRgyUCPDpxIOBqZaW2c',
    appId: '1:536987531282:ios:fa82e082ea20e3aa9cc0cb',
    messagingSenderId: '536987531282',
    projectId: 'taskflow-a6f6e',
    storageBucket: 'taskflow-a6f6e.firebasestorage.app',
    iosBundleId: 'com.dantech.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_aq_1uEhml4sdiRgyUCPDpxIOBqZaW2c',
    appId: '1:536987531282:ios:fa82e082ea20e3aa9cc0cb',
    messagingSenderId: '536987531282',
    projectId: 'taskflow-a6f6e',
    storageBucket: 'taskflow-a6f6e.firebasestorage.app',
    iosBundleId: 'com.dantech.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX9LbjWBeKL7jbpZmRL2Au4leq5bEIo0Y',
    appId: '1:536987531282:web:304cea02ef3547e49cc0cb',
    messagingSenderId: '536987531282',
    projectId: 'taskflow-a6f6e',
    authDomain: 'taskflow-a6f6e.firebaseapp.com',
    storageBucket: 'taskflow-a6f6e.firebasestorage.app',
  );

}