server {
  listen 80;
  server_name dev.taskflow.dan-tech.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 8444 ssl;
  server_name dev.taskflow.dan-tech.com;

  client_max_body_size 50M;

  ssl_certificate /etc/letsencrypt/live/taskflow.dan-tech.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/taskflow.dan-tech.com/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location ~* ^/(assets)/ {
      try_files $uri =404;
      expires 1y;
      access_log off;
  }

  location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://backend-dev:3000;
  }
}

server {
  listen 80;
  server_name dev.cdn.dan-tech.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 8444 ssl;
  server_name dev.cdn.dan-tech.com;

  ssl_certificate /etc/letsencrypt/live/taskflow.dan-tech.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/taskflow.dan-tech.com/privkey.pem;

  location ^~ /files/inline-images/ {
    alias /var/www/cdn_files/inline-images/; 
    autoindex off;
    add_header Access-Control-Allow-Origin *;
  }

  location ^~ /files/suppliers/ {
    alias /var/www/cdn_files/suppliers/;
    autoindex off;
    add_header Access-Control-Allow-Origin *;
  }

  location ^~ /files/ {
    return 403;
  }
}
