# Reject HTTPS requests for unknown hostnames.
server {
  listen 443 ssl default_server;
  server_name _;
  ssl_reject_handshake on;
}

# Production domains.
server {
  listen 443 ssl;
  http2 on;
  server_name taskflow.dan-tech.com cdn.dan-tech.com;

  ssl_certificate /etc/letsencrypt/live/taskflow.dan-tech.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/taskflow.dan-tech.com/privkey.pem;

  client_max_body_size 50M;
  resolver 127.0.0.11 valid=30s ipv6=off;

  location / {
    set $prod_frontend frontend-prod:8443;
    proxy_pass https://$prod_frontend;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    proxy_ssl_server_name on;
    proxy_ssl_name $host;
  }
}

# Development domains.
server {
  listen 443 ssl;
  http2 on;
  server_name dev.taskflow.dan-tech.com dev.cdn.dan-tech.com;

  ssl_certificate /etc/letsencrypt/live/taskflow.dan-tech.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/taskflow.dan-tech.com/privkey.pem;

  client_max_body_size 50M;
  resolver 127.0.0.11 valid=30s ipv6=off;

  location / {
    set $dev_frontend frontend-dev:8444;
    proxy_pass https://$dev_frontend;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    proxy_ssl_server_name on;
    proxy_ssl_name $host;
  }
}
