import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:math' as math;

// Shared presentation widgets and their feature-grouped parts.

import 'package:appflowy_editor/appflowy_editor.dart';
import 'package:dio/dio.dart';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter_svg/svg.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart' hide Provider;
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as path;
import 'package:provider/provider.dart' hide FutureProvider;
import 'package:intl/intl.dart';
import 'package:material_symbols_icons/symbols.dart';
import 'package:skeletonizer/skeletonizer.dart';
import 'package:taskflow/src/core/core.dart';
import 'package:taskflow/src/data/data.dart';
import 'package:taskflow/src/presentation/controller/controller.dart';
import 'package:taskflow/src/router/router.dart';
import 'package:taskflow/src/shared/tool/functions.dart';
import 'package:taskflow/src/shared/tool/responsive.dart';
import 'package:desktop_drop/desktop_drop.dart';
import 'package:loading_animation_widget/loading_animation_widget.dart';
import 'package:gpt_markdown/gpt_markdown.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:super_clipboard/super_clipboard.dart';

part 'widget.freezed.dart';

part 'attachment/attachment.dart';
part 'calendar/calendar.dart';
part 'controls/button.dart';
part 'controls/dropdown.dart';
part 'display/category.dart';
part 'display/client_information.dart';
part 'display/data_table.dart';
part 'display/logo.dart';
part 'display/markdown.dart';
part 'display/progress_bar.dart';
part 'display/user_information.dart';
part 'dialog/base_dialog.dart';
part 'dialog/date_picker_dialog.dart';
part 'dialog/navigation_search_dialog.dart';
part 'dialog/send_email_dialog.dart';
part 'dialog/user_selector_dialog.dart';
part 'editor/editor_widget.dart';
part 'editor/link_overlay.dart';
part 'editor/palette_overlay.dart';
part 'editor/toolbar_overlay.dart';
part 'feedback/overlay.dart';
part 'feedback/toast.dart';
part 'feedback/validation.dart';
part 'layout/bento_grid.dart';
part 'layout/container.dart';
part 'layout/sliver_app_bar_delegate.dart';
part 'model/bottom_sheet_item.dart';
part 'model/dashboard_model.dart';
part 'model/navigation_item.dart';
part 'model/validation_item.dart';
part 'navigation/dashboard_drawer.dart';
part 'preset/account_preset.dart';
part 'preset/auth_preset.dart';
part 'preset/common_preset.dart';
part 'preset/dashboard_preset.dart';
part 'preset/data_preset.dart';
part 'preset/document_preset.dart';
part 'preset/navigation_preset.dart';
part 'preset/project_preset.dart';
part 'preset/schedule_preset.dart';
part 'preset/work_preset.dart';
part 'preset/widget_preset.dart';
